[package]
name = "blueprince-numeric-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"
crossterm = "0.29.0"
derive_more = { version = "2.1.1", features = ["display"] }
itertools = "0.14.0"
ratatui = "0.29.0"
